// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoDWGlib7hKyFOIR4RQr7Hp9XcjxrP7l0',
    appId: '1:946282524275:web:fdd5089b2a6b48d0070406',
    messagingSenderId: '946282524275',
    projectId: 'medinoteai-2',
    authDomain: 'medinoteai-2.firebaseapp.com',
    storageBucket: 'medinoteai-2.firebasestorage.app',
    measurementId: 'G-2X89X7ENLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRZEKvjuDDZZF3sSkugK4fgswPpExn-ts',
    appId: '1:946282524275:android:f42a8a66d4cc267e070406',
    messagingSenderId: '946282524275',
    projectId: 'medinoteai-2',
    storageBucket: 'medinoteai-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpmeOJ6Zqw4XAZVKu9whesHUKFlLwoTKs',
    appId: '1:946282524275:ios:ced2c3322ffabd67070406',
    messagingSenderId: '946282524275',
    projectId: 'medinoteai-2',
    storageBucket: 'medinoteai-2.firebasestorage.app',
    androidClientId: '946282524275-9rfa122pb2or4c6cs5r2fvhop0ka7hbh.apps.googleusercontent.com',
    iosClientId: '946282524275-70c124ei95jecvft5v1lbrikndtfde50.apps.googleusercontent.com',
    iosBundleId: 'com.svacron.apps.medinoteai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpmeOJ6Zqw4XAZVKu9whesHUKFlLwoTKs',
    appId: '1:946282524275:ios:ced2c3322ffabd67070406',
    messagingSenderId: '946282524275',
    projectId: 'medinoteai-2',
    storageBucket: 'medinoteai-2.firebasestorage.app',
    androidClientId: '946282524275-9rfa122pb2or4c6cs5r2fvhop0ka7hbh.apps.googleusercontent.com',
    iosClientId: '946282524275-70c124ei95jecvft5v1lbrikndtfde50.apps.googleusercontent.com',
    iosBundleId: 'com.svacron.apps.medinoteai',
  );

}